/**
 * ---------------------
 * 🚗🚦 Generated by nuxt-typed-router. Do not modify !
 * ---------------------
 * */

import { defineNuxtPlugin } from '#app';

export default defineNuxtPlugin((nuxtApp) => {
  const routesList = {
    homeEn: 'home___en',
    homeZhCn: 'home___zh-CN',
    homeZhTw: 'home___zh-TW',
    indexEn: 'index___en',
    indexZhCn: 'index___zh-CN',
    indexZhTw: 'index___zh-TW',
  };

  return {
    provide: {
      typedRouter: nuxtApp.$router,
      routesList,
    },
  };
});
